version: 2

registries:
  - type: "npm-registry"
    url: "https://npm.pkg.github.com"
    token: "${{ secrets.BOT_TOKEN }}"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "daily"
    registries:
      - use-nyte
