name: Publish @use-nyte/eslint-config Package

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
              with:
                  version: 10.33.2
            - uses: actions/setup-node@v6
              with:
                  node-version: 24.15.0
                  cache: pnpm
            - run: pnpm install --frozen-lockfile

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
              with:
                  version: 10.33.2
            - uses: actions/setup-node@v6
              with:
                  node-version: 24.15.0
                  registry-url: https://npm.pkg.github.com/
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - run: pnpm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.BOT_TOKEN}}
